### ISSUE TITLE
xtelnet dependency on telnetlib. DeprecationWarning: 'telnetlib' is deprecated and slated for removal in Python 3.13

### ISSUE THREAD

**Issue by WrongGitUsername** [AlaBouali/xtelnet#6]
At a first glance xtelnet looked like exactly what i needed. So i started a test project with it to see if it can be used in production and test how it`s handling multi threading. 

After looking under the hood, i notice that it`s making use of telnetlib. :( 
As you (probably) already know, telnetlib will be removed in Python 3.13. 

See [PEP 594](https://peps.python.org/pep-0594/#deprecated-modules).

If we want xtelnet to have a long life, maybe start moving it to telnetlib3 or Exscript.

**Comment by AlaBouali** [comment]
thanks for letting me know! i believe that i should just create a fully custom one from scratch. i was going for that from the beginning then i changed my mind after that.

like i said, i don't worry ! i got your back guys ;)

**Comment by AlaBouali** [comment]
hello there my friend,

i apologize for the delay, i didn't find any clear documentation how to parse and respond to telnet negotiations but it turns out that i can skip them since they are only used to better present the output on the user's terminal. since xtelnet is not presenting them , i skipped that and tested it on several telnet servers and the results were promising ! please check the new documentation and much cleaner and readable code.

thank you for using xtelnet.
